config/routes.rb
Sklep::Application.routes.draw do
  devise_for :admins

  devise_for :users

  root :to => 'home#index'

  resources :products
  resources :cart_items
  resources :orders

  namespace "admin" do
    resources :products
    resources :orders
  end
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  # :registerable, :recoverable, :rememberable, :trackable
  devise :database_authenticatable, :validatable, :timeoutable,
	 :timeout_in => 20.minutes

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  has_many :products, :through => :cart_items
  has_one :order

  def make_order(params)
    @order = Order.create(params)
    @order.cart_id = self.id
    @order.save
    self.blocked = true
    self.save
  end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @orders = Order.all
    
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_filter :authenticate_admin!

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(params[:product])
    if @product == nil
      render new_admin_product_path
    else
      redirect_to admin_products_path
    end  

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to admin_products_path
    else
      render edit_admin_product_path
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def new
    if session[:cart_id] == nil
      @cart = Cart.create()
      session[:cart_id] = @cart.id
    else
      @cart = Cart.find(session[:cart_id])
    end

    @cart_item = CartItem.new
    @product = Product.find(params[:product_id])
    
    redirect_to edit_cart_item_path(@cart.cart_items.select{|i| i.product.id == @product.id}.first) if @cart.products.include?(@product)
  end
  
  def create
    @cart = Cart.find(session[:cart_id])
    @cart_item = @cart.cart_items.create(params[:cart_item])
    redirect_to root_path
  end

  def edit
    @cart_item = CartItem.find(params[:id])
  end

  def update
    @cart = Cart.find(session[:cart_id])
    @cart_item = @cart.cart_items.find(params[:id])
    if @cart_item.update_attributes(params[:cart_item])
      redirect_to root_path
    else
      render edit_cart_item_path
    end
  end

  def destroy
    @cart = Cart.find(session[:cart_id])
    @cart_item = @cart.cart_items.find(params[:id])
    @cart_item.destroy
    redirect_to root_path
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cart = Cart.find(session[:cart_id]) if session[:cart_id] != nil
    @products = Product.all    
    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @cart = Cart.find(session[:cart_id]) if session[:cart_id] != nil
    @order = Order.new
    redirect_to root_path if @cart == nil
  end

  def create
    @cart = Cart.find(session[:cart_id]) if session[:cart_id] != nil
    if @cart == nil
      redirect_to root_path, :notice => 'Koszyk jest pusty!'
    else    
      @cart.make_order(params[:order])
      session[:cart_id] = nil
      redirect_to root_path, :notice => 'Zamówienie zostało złożone'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @cart = Cart.find(session[:cart_id]) if session[:cart_id] != nil
    @products = Product.all
  end

  def show
    @cart = Cart.find(session[:cart_id]) if session[:cart_id] != nil
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/orders/index.html.haml
= @orders.size.to_s
- @orders.each do |o|
  %hr
  %p= o.address
  = #render :partial => 'cart/cart_div', :locals => {:cart => o.cart}
  - sum = 0
  - o.cart.cart_items.each do |i|
    %p 
      - price = i.quantity * i.product.price
      - sum += price
      =i.product.name + ' x ' + i.quantity.to_s + ' = ' + price.to_s
    %p= 'razem: ' + sum.to_s

app/views/admin/products/_form.html.haml
- form_for([:admin,product]) do |f|
  %p= f.label :name, "Nazwa:"
  %p= f.text_field :name
  %p= f.label :price, "Cena:"
  %p= f.text_field :price
  %p= f.submit submit_label

app/views/admin/products/edit.html.haml
= render :partial => 'form', :locals => {:product => @product, :submit_label => "Edytuj"}
 

app/views/admin/products/index.html.haml
%p= link_to "Dodaj Produkt", new_admin_product_path
Lista produktów:

- @products.each do |p|
  %p= link_to p.name, product_path(p.id)
  = 'cena: ' + p.price.to_s
  = link_to "Edytuj", edit_admin_product_path(p.id)
  = link_to "Usuń", admin_product_path(p.id), :method => 'delete'

app/views/admin/products/new.html.haml
= render :partial => 'form', :locals => {:product => @product, :submit_label => "Dodaj"}

app/views/cart/_cart_div.html.haml
#cart
  Koszyk
  - if @cart != nil and not @cart.cart_items.empty?
    - sum = 0
    - @cart.cart_items.each do |i|
      - sum += i.quantity * i.product.price
      %hr
      %p
        = i.product.name
        = link_to "Usuń", cart_item_path(i.id), :method => 'delete'
      %p
        = 'sztuk: ' + i.quantity.to_s
        = link_to "Zmień", edit_cart_item_path(i.id)
    %hr
    %p= 'Razem: ' + sum.to_s
    %p= link_to "Złóż zamówienie", new_order_path
  - else
    pusty 

app/views/cart_items/edit.html.haml
Edytujesz pozycję na zamówieniu
%p= @cart_item.product.name
%p= @cart_item.product.price
- form_for @cart_item do |f|
  %p= f.label :quantity, "Ilość: "
  %p= f.text_field :quantity
  %p= f.submit "Zmień"

app/views/cart_items/new.html.haml
Dodajesz produkt do koszyka:
%p= @product.name
%p= 'cena: ' + @product.price.to_s
- form_for @cart_item do |f|
  %p= f.label :quantity, "Ilość: "
  %p= f.text_field :quantity
  %p= hidden_field(:cart_item, :product_id, {:value => @product.id})
  %p= f.submit "Dodaj"

app/views/home/index.html.haml
- @products.each do |p|
  %p= link_to p.name, p

= render 'cart/cart_div'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sklep</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= link_to "Home", root_path%>

<% if admin_signed_in? %>
<%= link_to "Wyloguj się adminie", destroy_admin_session_path %>
<%= link_to "Produkty", admin_products_path %>
<%= link_to "Zamówienia", admin_orders_path %>
<% else %>
<%= link_to "Zaloguj się adminie", new_admin_session_path %>
login: admin@gmail.com, hasło: heroku
<% end %>


<hr>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/orders/new.html.haml
= render :partial => 'cart/cart_div', :locals => {:cart => @cart}
- form_for @order do |f|
  %p= f.label :address, "Dane adresowe: "
  %p= f.text_area:address
  %p= f.submit "Zamów"

app/views/products/show.html.haml
%h1= @product.name
%p= 'cena: ' + @product.price.to_s
%p= link_to "Dodaj do koszyka", new_cart_item_path(:product_id => @product.id)

= render :partial => 'cart/cart_div'